name: renovate
on:
  schedule:
  - cron: '0/30 * * * *'
jobs:
  renovate:
    runs-on: dind-runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Run Renovate
      uses: eidp/actions-common/renovate@8fb490fa25c3ae68beddc97b2430e5c586dc79e1 # v1.3.3
      with:
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}
