name: renovate
on:
  schedule:
  - cron: '0/30 * * * *'
jobs:
  renovate:
    runs-on: dind-runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Run Renovate
      uses: eidp/actions-common/renovate@8fb490fa25c3ae68beddc97b2430e5c586dc79e1 # v1.3.3
      with:
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}
